name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: SEU-USUARIO
          outputs: dist/github-snake.svg
          snake_color: "#39FF14"          # cor da cobrinha (verde neon)
          background_color: "#000000"     # fundo preto
          grid_color: "#444444"           # cor da grade

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
